version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: project_manager
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
